/**
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 4.0.0
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LaunchDarklyApi) {
      root.LaunchDarklyApi = {};
    }
    root.LaunchDarklyApi.FeatureFlagApprovalRequestReviewStatus = factory(root.LaunchDarklyApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class FeatureFlagApprovalRequestReviewStatus.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "pending"
     * @const
     */
    "pending": "pending",
    /**
     * value: "approved"
     * @const
     */
    "approved": "approved",
    /**
     * value: "declined"
     * @const
     */
    "declined": "declined"  };

  /**
   * Returns a <code>FeatureFlagApprovalRequestReviewStatus</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/FeatureFlagApprovalRequestReviewStatus} The enum <code>FeatureFlagApprovalRequestReviewStatus</code> value.
   */
  exports.constructFromObject = function(object) {
    return object;
  }

  return exports;
}));


