/**
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.0.1
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/IntegrationLinks', 'model/IntegrationSubscription'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./IntegrationLinks'), require('./IntegrationSubscription'));
  } else {
    // Browser globals (root is window)
    if (!root.LaunchDarklyApi) {
      root.LaunchDarklyApi = {};
    }
    root.LaunchDarklyApi.Integration = factory(root.LaunchDarklyApi.ApiClient, root.LaunchDarklyApi.IntegrationLinks, root.LaunchDarklyApi.IntegrationSubscription);
  }
}(this, function(ApiClient, IntegrationLinks, IntegrationSubscription) {
  'use strict';




  /**
   * The Integration model module.
   * @module model/Integration
   * @version 5.0.1
   */

  /**
   * Constructs a new <code>Integration</code>.
   * @alias module:model/Integration
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>Integration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Integration} obj Optional instance to populate.
   * @return {module:model/Integration} The populated <code>Integration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_links')) {
        obj['_links'] = IntegrationLinks.constructFromObject(data['_links']);
      }
      if (data.hasOwnProperty('items')) {
        obj['items'] = ApiClient.convertToType(data['items'], [IntegrationSubscription]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/IntegrationLinks} _links
   */
  exports.prototype['_links'] = undefined;
  /**
   * @member {Array.<module:model/IntegrationSubscription>} items
   */
  exports.prototype['items'] = undefined;



  return exports;
}));


