/**
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 3.3.1
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LaunchDarklyApi) {
      root.LaunchDarklyApi = {};
    }
    root.LaunchDarklyApi.SemanticPatchOperationInstructions = factory(root.LaunchDarklyApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SemanticPatchOperationInstructions model module.
   * @module model/SemanticPatchOperationInstructions
   * @version 3.3.1
   */

  /**
   * Constructs a new <code>SemanticPatchOperationInstructions</code>.
   * @alias module:model/SemanticPatchOperationInstructions
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>SemanticPatchOperationInstructions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SemanticPatchOperationInstructions} obj Optional instance to populate.
   * @return {module:model/SemanticPatchOperationInstructions} The populated <code>SemanticPatchOperationInstructions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('kind')) {
        obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
      }
    }
    return obj;
  }

  /**
   * The name of the modification you would like to perform on a resource.
   * @member {String} kind
   */
  exports.prototype['kind'] = undefined;



  return exports;
}));


