/**
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 3.6.0
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LaunchDarklyApi) {
      root.LaunchDarklyApi = {};
    }
    root.LaunchDarklyApi.UnboundedSegmentTargetChanges = factory(root.LaunchDarklyApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The UnboundedSegmentTargetChanges model module.
   * @module model/UnboundedSegmentTargetChanges
   * @version 3.6.0
   */

  /**
   * Constructs a new <code>UnboundedSegmentTargetChanges</code>.
   * @alias module:model/UnboundedSegmentTargetChanges
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>UnboundedSegmentTargetChanges</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UnboundedSegmentTargetChanges} obj Optional instance to populate.
   * @return {module:model/UnboundedSegmentTargetChanges} The populated <code>UnboundedSegmentTargetChanges</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('add')) {
        obj['add'] = ApiClient.convertToType(data['add'], ['String']);
      }
      if (data.hasOwnProperty('remove')) {
        obj['remove'] = ApiClient.convertToType(data['remove'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Users to add to this list of targets
   * @member {Array.<String>} add
   */
  exports.prototype['add'] = undefined;
  /**
   * Users to remove from this list of targets
   * @member {Array.<String>} remove
   */
  exports.prototype['remove'] = undefined;



  return exports;
}));


