/*
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.0.3
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LaunchDarklyApi);
  }
}(this, function(expect, LaunchDarklyApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Rollout', function() {
      beforeEach(function() {
        instance = new LaunchDarklyApi.Rollout();
      });

      it('should create an instance of Rollout', function() {
        // TODO: update the code to test Rollout
        expect(instance).to.be.a(LaunchDarklyApi.Rollout);
      });

      it('should have the property bucketBy (base name: "bucketBy")', function() {
        // TODO: update the code to test the property bucketBy
        expect(instance).to.have.property('bucketBy');
        // expect(instance.bucketBy).to.be(expectedValueLiteral);
      });

      it('should have the property variations (base name: "variations")', function() {
        // TODO: update the code to test the property variations
        expect(instance).to.have.property('variations');
        // expect(instance.variations).to.be(expectedValueLiteral);
      });

    });
  });

}));
