/*
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.1.0
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LaunchDarklyApi);
  }
}(this, function(expect, LaunchDarklyApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Rule', function() {
      beforeEach(function() {
        instance = new LaunchDarklyApi.Rule();
      });

      it('should create an instance of Rule', function() {
        // TODO: update the code to test Rule
        expect(instance).to.be.a(LaunchDarklyApi.Rule);
      });

      it('should have the property id (base name: "_id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property variation (base name: "variation")', function() {
        // TODO: update the code to test the property variation
        expect(instance).to.have.property('variation');
        // expect(instance.variation).to.be(expectedValueLiteral);
      });

      it('should have the property trackEvents (base name: "trackEvents")', function() {
        // TODO: update the code to test the property trackEvents
        expect(instance).to.have.property('trackEvents');
        // expect(instance.trackEvents).to.be(expectedValueLiteral);
      });

      it('should have the property rollout (base name: "rollout")', function() {
        // TODO: update the code to test the property rollout
        expect(instance).to.have.property('rollout');
        // expect(instance.rollout).to.be(expectedValueLiteral);
      });

      it('should have the property clauses (base name: "clauses")', function() {
        // TODO: update the code to test the property clauses
        expect(instance).to.have.property('clauses');
        // expect(instance.clauses).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

    });
  });

}));
