/*
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 5.1.0
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LaunchDarklyApi);
  }
}(this, function(expect, LaunchDarklyApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Statement', function() {
      beforeEach(function() {
        instance = new LaunchDarklyApi.Statement();
      });

      it('should create an instance of Statement', function() {
        // TODO: update the code to test Statement
        expect(instance).to.be.a(LaunchDarklyApi.Statement);
      });

      it('should have the property resources (base name: "resources")', function() {
        // TODO: update the code to test the property resources
        expect(instance).to.have.property('resources');
        // expect(instance.resources).to.be(expectedValueLiteral);
      });

      it('should have the property notResources (base name: "notResources")', function() {
        // TODO: update the code to test the property notResources
        expect(instance).to.have.property('notResources');
        // expect(instance.notResources).to.be(expectedValueLiteral);
      });

      it('should have the property actions (base name: "actions")', function() {
        // TODO: update the code to test the property actions
        expect(instance).to.have.property('actions');
        // expect(instance.actions).to.be(expectedValueLiteral);
      });

      it('should have the property notActions (base name: "notActions")', function() {
        // TODO: update the code to test the property notActions
        expect(instance).to.have.property('notActions');
        // expect(instance.notActions).to.be(expectedValueLiteral);
      });

      it('should have the property effect (base name: "effect")', function() {
        // TODO: update the code to test the property effect
        expect(instance).to.have.property('effect');
        // expect(instance.effect).to.be(expectedValueLiteral);
      });

    });
  });

}));
