/**
 * LaunchDarkly REST API
 * Build custom integrations with the LaunchDarkly REST API
 *
 * OpenAPI spec version: 3.6.0
 * Contact: support@launchdarkly.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LaunchDarklyApi);
  }
}(this, function(expect, LaunchDarklyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LaunchDarklyApi.RelayProxyConfigurationsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RelayProxyConfigurationsApi', function() {
    describe('deleteRelayProxyConfig', function() {
      it('should call deleteRelayProxyConfig successfully', function(done) {
        //uncomment below and update the code to test deleteRelayProxyConfig
        //instance.deleteRelayProxyConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRelayProxyConfig', function() {
      it('should call getRelayProxyConfig successfully', function(done) {
        //uncomment below and update the code to test getRelayProxyConfig
        //instance.getRelayProxyConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getRelayProxyConfigs', function() {
      it('should call getRelayProxyConfigs successfully', function(done) {
        //uncomment below and update the code to test getRelayProxyConfigs
        //instance.getRelayProxyConfigs(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchRelayProxyConfig', function() {
      it('should call patchRelayProxyConfig successfully', function(done) {
        //uncomment below and update the code to test patchRelayProxyConfig
        //instance.patchRelayProxyConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postRelayAutoConfig', function() {
      it('should call postRelayAutoConfig successfully', function(done) {
        //uncomment below and update the code to test postRelayAutoConfig
        //instance.postRelayAutoConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resetRelayProxyConfig', function() {
      it('should call resetRelayProxyConfig successfully', function(done) {
        //uncomment below and update the code to test resetRelayProxyConfig
        //instance.resetRelayProxyConfig(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
